[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "roster-generator"
version = "0.0.3"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "numpy",
    "airportsdata",
    "aircraft-list",
    "pytz",
]
